$(document).ready(function(){function e(){$(".top-case-detail-hero").css({height:$(window).width()/4.8})}var t=window.History
navBarAnimate(),addBrowerBodyClass($("body")),removeLastSectionDevider(),menuTrigger("#menu-trigger","#full-screen-menu","header"),$(".dot-point").length>0&&(dotToDot(),$(".vertical-ruler").css({left:$(".dot-point:first-child").offset().left-$(".dot-point:first-child").parent().offset().left})),doItOnResizeFn(e),$(".loadHtmlContent").click(function(e){function n(e){return $.ajax({url:e,type:"get",dataType:"html"})}e.preventDefault()
var i=$(this).find(".case-block"),o=i.offset(),a=o.top-$(document).scrollTop(),r=o.left-$(document).scrollLeft(),d=$(this).data("image-hd")
i.delay(400).css({height:i.outerHeight(),width:i.outerWidth(),top:a,left:r,"z-index":"9999",position:"fixed"}),$(".add-me-here").append(i),i=$(".add-me-here").find(".case-block"),$(".cases-contetnt, .hp-negative, .we-recommend-cont, .logotips, .in-case-block-row").fadeOut(400,function(){$(this).remove()}),$("header, footer, .page-title").fadeOut(400,function(){$(this).css({opacity:"0","-webkit-animation":"none","-o-animation":"none",animation:"none",display:"block"})}),$("body").addClass("case cases-detail")
var s=$(this).data("id"),l=$(document).find(".loadAjaxTitle").data("page-title-url")+"&id="+s,c=$(document).find(".loadAjaxTitle").data("page-content-url")+"&id="+s
n(l).done(function(e){$(".title-result").html(e)
var t=$(document).find(".title-result h1").text(),n=$(document).find(".title-result h6").text()
$(document).find(".inner-page-title h1").text(t).css({position:"relative",top:"50px"}),$(document).find(".inner-page-title h6").text(n).css({position:"relative",top:"50px"})
var o=$(document).find("header").outerHeight(),a=$(document).find(".page-title").outerHeight(),r=o+a
i.delay(400).animate({top:r,left:0,width:"100%",height:450},800,function(){$(this).css({position:"",top:"",width:"","z-index":""}),i.delay(800).queue(function(){$(this).css({"background-size":"contain","background-image":"url("+d+")"})}),$("body").removeClass("home-page"),$("header, .page-title").delay(400).animate({opacity:1},400),$(document).find(".inner-page-title h1, .inner-page-title h6").delay(400).animate({top:"0"},400),$(".content-result").fadeIn(400).animate({opacity:1,"margin-top":"0"},400),$("footer").fadeIn(400).removeAttr("style"),$(document).prop("title",$(document).find(".inner-page-title h6").text()+" - Folkmatic"),$("html, body").delay(400).animate({scrollTop:0},0),(new WOW).init(),removeLastSectionDevider()})}),n(c).done(function(e){$(".content-result").hide().load(c),$(document).find(".content-result").css({height:"auto","margin-top":"50px"})})
var u=$(this).data("href"),h={state:1}
t.pushState(h,null,u)}),carouselActive(".carousel-inner",".carousel-item")}),$(window).load(function(){var e=$(".inner-mover"),t=$(".inner-movers-wrapper"),n=(window.location.href,$(".case-block"))
n.on("mouseover",animateIlustration),setInnerMoverWrapperHeight(findBiggestInnerMover(e),t,768),$(window).resize(function(){setInnerMoverWrapperHeight(findBiggestInnerMover(e),t,768)}),(new WOW).init(),makeFooterFixed(),heroImageSize(".small-res-bckg",1.77778),heroImageSize(".big-res-bckg",3.555556),heroImageSize(".big-res-bckg-about",2.1333333),responsiveBlock($(".case-block-single-sase"),2,210,450)
$("body").html()
History.Adapter.bind(window,"statechange",function(){var e=History.getState();(e.url==homePageUrl+"/"||e.url==homePageUrl+"/cases/")&&window.location.reload()})})
